# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from laser_line_extraction/ParkingInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ParkingInfo(genpy.Message):
  _md5sum = "d4b96bd09ad1afc3b3dc969864e27d31"
  _type = "laser_line_extraction/ParkingInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool isParking

float32 width
float32 depth

float32 top_y
float32 bottom_y
float32 out_x
float32 in_x"""
  __slots__ = ['isParking','width','depth','top_y','bottom_y','out_x','in_x']
  _slot_types = ['bool','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isParking,width,depth,top_y,bottom_y,out_x,in_x

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ParkingInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.isParking is None:
        self.isParking = False
      if self.width is None:
        self.width = 0.
      if self.depth is None:
        self.depth = 0.
      if self.top_y is None:
        self.top_y = 0.
      if self.bottom_y is None:
        self.bottom_y = 0.
      if self.out_x is None:
        self.out_x = 0.
      if self.in_x is None:
        self.in_x = 0.
    else:
      self.isParking = False
      self.width = 0.
      self.depth = 0.
      self.top_y = 0.
      self.bottom_y = 0.
      self.out_x = 0.
      self.in_x = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6f().pack(_x.isParking, _x.width, _x.depth, _x.top_y, _x.bottom_y, _x.out_x, _x.in_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.isParking, _x.width, _x.depth, _x.top_y, _x.bottom_y, _x.out_x, _x.in_x,) = _get_struct_B6f().unpack(str[start:end])
      self.isParking = bool(self.isParking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6f().pack(_x.isParking, _x.width, _x.depth, _x.top_y, _x.bottom_y, _x.out_x, _x.in_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.isParking, _x.width, _x.depth, _x.top_y, _x.bottom_y, _x.out_x, _x.in_x,) = _get_struct_B6f().unpack(str[start:end])
      self.isParking = bool(self.isParking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6f = None
def _get_struct_B6f():
    global _struct_B6f
    if _struct_B6f is None:
        _struct_B6f = struct.Struct("<B6f")
    return _struct_B6f
