(cl:defpackage romi_interface-msg
  (:use )
  (:export
   "<FOLLOW_PATHACTION>"
   "FOLLOW_PATHACTION"
   "<FOLLOW_PATHACTIONFEEDBACK>"
   "FOLLOW_PATHACTIONFEEDBACK"
   "<FOLLOW_PATHACTIONGOAL>"
   "FOLLOW_PATHACTIONGOAL"
   "<FOLLOW_PATHACTIONRESULT>"
   "FOLLOW_PATHACTIONRESULT"
   "<FOLLOW_PATHFEEDBACK>"
   "FOLLOW_PATHFEEDBACK"
   "<FOLLOW_PATHGOAL>"
   "FOLLOW_PATHGOAL"
   "<FOLLOW_PATHRESULT>"
   "FOLLOW_PATHRESULT"
  ))

