; Auto-generated. Do not edit!


(cl:in-package romi_interface-msg)


;//! \htmlinclude follow_pathActionGoal.msg.html

(cl:defclass <follow_pathActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type romi_interface-msg:follow_pathGoal
    :initform (cl:make-instance 'romi_interface-msg:follow_pathGoal)))
)

(cl:defclass follow_pathActionGoal (<follow_pathActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <follow_pathActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'follow_pathActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name romi_interface-msg:<follow_pathActionGoal> is deprecated: use romi_interface-msg:follow_pathActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <follow_pathActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader romi_interface-msg:header-val is deprecated.  Use romi_interface-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <follow_pathActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader romi_interface-msg:goal_id-val is deprecated.  Use romi_interface-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <follow_pathActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader romi_interface-msg:goal-val is deprecated.  Use romi_interface-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <follow_pathActionGoal>) ostream)
  "Serializes a message object of type '<follow_pathActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <follow_pathActionGoal>) istream)
  "Deserializes a message object of type '<follow_pathActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<follow_pathActionGoal>)))
  "Returns string type for a message object of type '<follow_pathActionGoal>"
  "romi_interface/follow_pathActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'follow_pathActionGoal)))
  "Returns string type for a message object of type 'follow_pathActionGoal"
  "romi_interface/follow_pathActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<follow_pathActionGoal>)))
  "Returns md5sum for a message object of type '<follow_pathActionGoal>"
  "d3955a6d4d1efe19491e62cf9c51a00a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'follow_pathActionGoal)))
  "Returns md5sum for a message object of type 'follow_pathActionGoal"
  "d3955a6d4d1efe19491e62cf9c51a00a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<follow_pathActionGoal>)))
  "Returns full string definition for message of type '<follow_pathActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%follow_pathGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: romi_interface/follow_pathGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'follow_pathActionGoal)))
  "Returns full string definition for message of type 'follow_pathActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%follow_pathGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: romi_interface/follow_pathGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <follow_pathActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <follow_pathActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'follow_pathActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
