; Auto-generated. Do not edit!


(cl:in-package romi_interface-msg)


;//! \htmlinclude follow_pathGoal.msg.html

(cl:defclass <follow_pathGoal> (roslisp-msg-protocol:ros-message)
  ((path
    :reader path
    :initarg :path
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass follow_pathGoal (<follow_pathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <follow_pathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'follow_pathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name romi_interface-msg:<follow_pathGoal> is deprecated: use romi_interface-msg:follow_pathGoal instead.")))

(cl:ensure-generic-function 'path-val :lambda-list '(m))
(cl:defmethod path-val ((m <follow_pathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader romi_interface-msg:path-val is deprecated.  Use romi_interface-msg:path instead.")
  (path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <follow_pathGoal>) ostream)
  "Serializes a message object of type '<follow_pathGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'path))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'path))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <follow_pathGoal>) istream)
  "Deserializes a message object of type '<follow_pathGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'path) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'path)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<follow_pathGoal>)))
  "Returns string type for a message object of type '<follow_pathGoal>"
  "romi_interface/follow_pathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'follow_pathGoal)))
  "Returns string type for a message object of type 'follow_pathGoal"
  "romi_interface/follow_pathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<follow_pathGoal>)))
  "Returns md5sum for a message object of type '<follow_pathGoal>"
  "7a8156bd9db798c344e3efbcdcb081c4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'follow_pathGoal)))
  "Returns md5sum for a message object of type 'follow_pathGoal"
  "7a8156bd9db798c344e3efbcdcb081c4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<follow_pathGoal>)))
  "Returns full string definition for message of type '<follow_pathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'follow_pathGoal)))
  "Returns full string definition for message of type 'follow_pathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <follow_pathGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'path) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <follow_pathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'follow_pathGoal
    (cl:cons ':path (path msg))
))
