; Auto-generated. Do not edit!


(cl:in-package romi_interface-msg)


;//! \htmlinclude follow_pathFeedback.msg.html

(cl:defclass <follow_pathFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass follow_pathFeedback (<follow_pathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <follow_pathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'follow_pathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name romi_interface-msg:<follow_pathFeedback> is deprecated: use romi_interface-msg:follow_pathFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <follow_pathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader romi_interface-msg:percent_complete-val is deprecated.  Use romi_interface-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <follow_pathFeedback>) ostream)
  "Serializes a message object of type '<follow_pathFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <follow_pathFeedback>) istream)
  "Deserializes a message object of type '<follow_pathFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<follow_pathFeedback>)))
  "Returns string type for a message object of type '<follow_pathFeedback>"
  "romi_interface/follow_pathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'follow_pathFeedback)))
  "Returns string type for a message object of type 'follow_pathFeedback"
  "romi_interface/follow_pathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<follow_pathFeedback>)))
  "Returns md5sum for a message object of type '<follow_pathFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'follow_pathFeedback)))
  "Returns md5sum for a message object of type 'follow_pathFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<follow_pathFeedback>)))
  "Returns full string definition for message of type '<follow_pathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'follow_pathFeedback)))
  "Returns full string definition for message of type 'follow_pathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <follow_pathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <follow_pathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'follow_pathFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
