// Generated by gencpp from file romi_interface/follow_pathActionGoal.msg
// DO NOT EDIT!


#ifndef ROMI_INTERFACE_MESSAGE_FOLLOW_PATHACTIONGOAL_H
#define ROMI_INTERFACE_MESSAGE_FOLLOW_PATHACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <romi_interface/follow_pathGoal.h>

namespace romi_interface
{
template <class ContainerAllocator>
struct follow_pathActionGoal_
{
  typedef follow_pathActionGoal_<ContainerAllocator> Type;

  follow_pathActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  follow_pathActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::romi_interface::follow_pathGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct follow_pathActionGoal_

typedef ::romi_interface::follow_pathActionGoal_<std::allocator<void> > follow_pathActionGoal;

typedef boost::shared_ptr< ::romi_interface::follow_pathActionGoal > follow_pathActionGoalPtr;
typedef boost::shared_ptr< ::romi_interface::follow_pathActionGoal const> follow_pathActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::romi_interface::follow_pathActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::romi_interface::follow_pathActionGoal_<ContainerAllocator1> & lhs, const ::romi_interface::follow_pathActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::romi_interface::follow_pathActionGoal_<ContainerAllocator1> & lhs, const ::romi_interface::follow_pathActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace romi_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3955a6d4d1efe19491e62cf9c51a00a";
  }

  static const char* value(const ::romi_interface::follow_pathActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3955a6d4d1efe19ULL;
  static const uint64_t static_value2 = 0x491e62cf9c51a00aULL;
};

template<class ContainerAllocator>
struct DataType< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romi_interface/follow_pathActionGoal";
  }

  static const char* value(const ::romi_interface::follow_pathActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"follow_pathGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: romi_interface/follow_pathGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"float32[] path\n"
;
  }

  static const char* value(const ::romi_interface::follow_pathActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct follow_pathActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::romi_interface::follow_pathActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::romi_interface::follow_pathActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::romi_interface::follow_pathGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROMI_INTERFACE_MESSAGE_FOLLOW_PATHACTIONGOAL_H
