// Generated by gencpp from file romi_interface/follow_pathFeedback.msg
// DO NOT EDIT!


#ifndef ROMI_INTERFACE_MESSAGE_FOLLOW_PATHFEEDBACK_H
#define ROMI_INTERFACE_MESSAGE_FOLLOW_PATHFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace romi_interface
{
template <class ContainerAllocator>
struct follow_pathFeedback_
{
  typedef follow_pathFeedback_<ContainerAllocator> Type;

  follow_pathFeedback_()
    : percent_complete(0.0)  {
    }
  follow_pathFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::romi_interface::follow_pathFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::romi_interface::follow_pathFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct follow_pathFeedback_

typedef ::romi_interface::follow_pathFeedback_<std::allocator<void> > follow_pathFeedback;

typedef boost::shared_ptr< ::romi_interface::follow_pathFeedback > follow_pathFeedbackPtr;
typedef boost::shared_ptr< ::romi_interface::follow_pathFeedback const> follow_pathFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::romi_interface::follow_pathFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::romi_interface::follow_pathFeedback_<ContainerAllocator1> & lhs, const ::romi_interface::follow_pathFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::romi_interface::follow_pathFeedback_<ContainerAllocator1> & lhs, const ::romi_interface::follow_pathFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace romi_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romi_interface::follow_pathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romi_interface::follow_pathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romi_interface::follow_pathFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::romi_interface::follow_pathFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romi_interface/follow_pathFeedback";
  }

  static const char* value(const ::romi_interface::follow_pathFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
;
  }

  static const char* value(const ::romi_interface::follow_pathFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct follow_pathFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::romi_interface::follow_pathFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::romi_interface::follow_pathFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROMI_INTERFACE_MESSAGE_FOLLOW_PATHFEEDBACK_H
